### ISSUE TITLE
Path problems on Windows

### ISSUE THREAD

**Issue by janpio** [fabiospampinato/banal#3]
As you write this has been written and tested on Mac, so no surprise that Windows paths cause trouble - as usual:

```
PS C:\Users\Jan\Documents\throwaway\bundle-size-experiments> pnpm banal .\_minimal\dist-esbuild\function.js
Temp path: C:\Users\Jan\AppData\Local\Temp\banal-7f2ffb657261320f458b5458ff2938b8
X [ERROR] Could not resolve "C:UsersJanDocuments\throwaway\bundle-size-experiments_minimaldist-esbuild\function.js"

    input.js:2:51:
      2 │ export * as _382e98417ea29bbdde569b661c183d24 from 'C:\Users\Jan\Documents\throwaway\bundle-size-experiments\_minimal\dist-esbuild\function.js';
        ╵                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path
  "C:UsersJanDocuments\throwaway\bundle-size-experiments_minimaldist-esbuild\function.js" as
  external to exclude it from the bundle, which will remove this error.

Error: Build failed with 1 error:
input.js:2:51: ERROR: Could not resolve "C:UsersJanDocuments\throwaway\bundle-size-experiments_minimaldist-esbuild\function.js"
    at failureErrorWithLog (C:\Users\Jan\Documents\throwaway\bundle-size-experiments\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649:15)
    at C:\Users\Jan\Documents\throwaway\bundle-size-experiments\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1058:25
    at C:\Users\Jan\Documents\throwaway\bundle-size-experiments\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1003:52
    at buildResponseToResult (C:\Users\Jan\Documents\throwaway\bundle-size-experiments\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1056:7)
    at C:\Users\Jan\Documents\throwaway\bundle-size-experiments\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1085:16
    at responseCallbacks.<computed> (C:\Users\Jan\Documents\throwaway\bundle-size-experiments\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:703:9)
    at handleIncomingPacket (C:\Users\Jan\Documents\throwaway\bundle-size-experiments\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:762:9)
    at Socket.readFromStdout (C:\Users\Jan\Documents\throwaway\bundle-size-experiments\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "C:UsersJanDocuments\\throwaway\\bundle-size-experiments_minimaldist-esbuild\\function.js"'
    }
  ],
  warnings: []
}
```

I'll see if I can figure it out and do a PR.

**Comment by fabiospampinato** [comment]
Fixed.
